// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL is not set. Copy backend/.env.example to backend/.env and set DATABASE_URL (e.g. postgresql://user:password@localhost:5432/insight_garden).",
  );
}
// Docker Compose Postgres is on port 5432. Wrong port (e.g. 51213) causes "Can't reach database server".
if (!databaseUrl.includes(":5432/") && !databaseUrl.includes(":5432?")) {
  console.error(
    "Warning: DATABASE_URL should use port 5432 for docker-compose Postgres. Current value may use a different port.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
