-- Instant activation (Phase 8): document summary + suggested questions,
-- generated by one LLM call at the end of processing (nullable — generation
-- is best-effort and lazily backfilled for existing documents).
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "summary" TEXT;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "suggested_questions" JSONB;
